appName: eldix
nameSpace: sberg-eldix

privateRegistry:
  name: ask-sberg
  imagePullSecret:
    create: true
    name: sberg-registry-pull-secret
    username: ask-sberg
    token: ask-sberg

appContainer:
  version: 2.8.0
  ## use: arm64 or amd64
  arch: arm64
  env:
    DB_HOST: eldix4kim-mariadb
    DB_ROOT_PASSWORD: doWhatYouWant!
    TZ: Europe/Berlin
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 300Mi
  imagePullPolicy: Always

dbContainer:
  skipDeployment: false
  version: 11.4.4
  ## use: arm64 or amd64
  arch: arm64
  env:
    MARIADB_ROOT_PASSWORD: doWhatYouWant!
    TZ: Europe/Berlin
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 150Mi
  imagePullPolicy: Always
