nameOverride:
fullnameOverride:

privateRegistry:
  name: ask-sberg
  imagePullSecret:
    create: true
    name: sberg-registry-pull-secret
    username: ask-sberg
    token: ask-sberg

## ingress config based on ingress-class nginx & cert manager Let's Encrypt
ingress:
  enabled: false
  annotations: {}
  #  kubernetes.io/ingress.class: nginx,
  #  cert-manager.io/cluster-issuer: letsencrypt-production,
  #  kubernetes.io/tls-acme: 'true',
  #  nginx.ingress.kubernetes.io/proxy-body-size: 1000m
  labels: {}
  path: /
  pathType: Prefix
  hostname: eldix.your-domain.com
  #tls:
  #  - secretName: eldix-tls
  #    hosts:
  #     - eldix.domain.de

eldix:
  image:
    ## full path and name of eldix image (e.g. repository/eldix-image)
    ## default: values from privateRegistry
    #repository:
    ## default: version from chart.yaml
    #version:
    pullPolicy: Always
  securityContext: {}
  nodeSelector: {}
  settings: {}
    #tz:
    #error_mail_address:
    #log_max_host:
    #log_max_file_size:
    #log_level:
    #app_profile:

  ## set NodePort for smtp service, if not port will be generated by kubernetes
  #smtpNodePort:

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi

  persistence:
    enabled: false
    ## If true will use an existing PVC instead of creating one
    #useExistingPVC:
    ## use default storageClass with ""
    ## disable auto storageClass with "-"
    storageClass: ""
    size: 30Gi
    #subPath:

  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 30

## use extern DB enable this and disable mariadb
externalDatabase:
  enabled: false
  hostname:
  database:
  username:
  password:

## use mariadb enable this and disable externalDatabase
mariadb:
  enabled: true
  auth:
    database: eldix4kim
    username: eldix
    password: eldix
  primary:
    persistence:
      enabled: false
      ## use default with ""
      storageClass: ""
      size: 5Gi
