appName: eldix
nameSpace: sberg

privateRegistry:
  name: ask-sberg
  imagePullSecret:
    create: true
    name: sberg-registry-pull-secret
    username: ask-sberg
    token: ask-sberg

securityContext:
  # settings has effects on all pods
  runAsUser: 1027
  runAsGroup: 1027
  fsGroup: 1027

appContainer:
  # overwrite default appVersion from chart.yaml
  version:
  ## possible arch's are: arm64, amd64
  arch: arm64
  env:
    DB-HOST: eldix-db
    DB-ROOT-PASSWORD: doWhatYouWant!
    VZD-LDAP-VAL-SSL-CERT: false
    TZ: Europe/Berlin
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi
  imagePullPolicy: Always

dbContainer:
  enabled: true
  # overwrite default mariaDB version 11.4.4
  version:
  # use any official mariaDB image arch (e.g. arm64, amd64)
  arch: arm64
  env:
    MARIADB_ROOT_PASSWORD: doWhatYouWant!
    TZ: Europe/Berlin
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi
  imagePullPolicy: Always

persistence:
  enabled: true
  ## If true will use an existing PVC instead of creating one
  #useExistingPVC: yourPVCName
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.
  #storageClass: "-"
  size: 10Gi
  subPath: eldix

  pv_static_nfs:
    enabled: false
    name: pv-nfs-static-eldix
    size: 10Gi
    nfs:
      path: /path-to-nfs-export
      server: NFS-Server-IP-Address
