appName: eldix
nameSpace: sberg

privateRegistry:
  name: ask-sberg
  imagePullSecret:
    create: true
    name: sberg-registry-pull-secret
    username: ask-sberg
    token: ask-sberg

appContainer:
  version: 2.9.0
  ## use: arm64 or amd64
  arch: arm64
  env:
    DB_HOST: eldix-db
    DB_ROOT_PASSWORD: doWhatYouWant!
    TZ: Europe/Berlin
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 300Mi
  imagePullPolicy: Always

dbContainer:
  enabled: true
  version: 11.4.4
  ## use: arm64 or amd64
  arch: arm64
  env:
    MARIADB_ROOT_PASSWORD: doWhatYouWant!
    TZ: Europe/Berlin
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 150Mi
  imagePullPolicy: Always

persistence:
  enabled: true
  ## If true will use an existing PVC instead of creating one
  # useExisting: false
  ## Name of existing PVC to be used in the influx deployment
  # name:

  useExistingPV:

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.
  # storageClass: "-"
  size: 20Gi
  subPath: eldix
