{{- if .Values.app.persistence.enabled  }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "data-{{ template "app.fullname" . }}-app"
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.app.persistence.size | quote }}
  {{- if .Values.app.persistence.storageClass }}
  {{- if (eq "-" .Values.app.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.app.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
