{{ if .Values.dbContainer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-db"
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-db"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}-db"
    spec:
      nodeSelector:
        kubernetes.io/arch: {{ .Values.dbContainer.arch }}
      containers:
        - env:
            - name: MARIADB_ROOT_PASSWORD
              value: {{ .Values.dbContainer.env.MARIADB_ROOT_PASSWORD }}
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: TZ
              value: {{ .Values.dbContainer.env.TZ}}
          image: "mariadb:{{ .Values.dbContainer.version }}"
          imagePullPolicy: {{ .Values.dbContainer.imagePullPolicy }}
          name: {{ .Values.appName }}
          {{ if .Values.persistence.enabled -}}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: eldix-data
              subPath: "{{ .Values.persistence.subPath }}/mariadb"
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.dbContainer.resources.limits.cpu }}
              memory: {{ .Values.dbContainer.resources.limits.memory }}
            requests:
              cpu: {{ .Values.dbContainer.resources.requests.cpu }}
              memory: {{ .Values.dbContainer.resources.requests.memory }}
      restartPolicy: Always
      {{ if .Values.persistence.enabled -}}
      volumes:
        - name: eldix-data
          persistentVolumeClaim:
            claimName: eldix
      {{- end }}
{{- end }}
