{{ if and .Values.privateRegistry.imagePullSecret.name .Values.privateRegistry.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privateRegistry.imagePullSecret.name }}
  namespace: {{ .Values.nameSpace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
