{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.appName }}-vhost"
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    helm.sh/chart: {{ include "eldix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.appName }}-app
                port:
                  number: 80
            path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.hostname }}-tls
  {{- end }}
{{- end }}
