{{- if and ( .Values.persistence.enabled ) ( not .Values.persistence.useExistingPVC ) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eldix
  namespace: {{ .Values.nameSpace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if or ( .Values.persistence.storageClass ) ( .Values.persistence.pv_static_nfs.enabled ) }}
  {{- if or (eq "-" .Values.persistence.storageClass) ( .Values.persistence.pv_static_nfs.enabled ) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.pv_static_nfs.enabled }}
  volumeName: {{ .Values.persistence.pv_static_nfs.name }}
  {{- end}}
{{- end }}
