{{- if and ( .Values.persistence.enabled ) ( not .Values.persistence.useExistingPVC ) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eldix
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    helm.sh/chart: {{ include "eldix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if or ( .Values.persistence.storageClass ) ( .Values.persistence.pv_static_nfs.enabled ) }}
  {{- if or (eq "-" .Values.persistence.storageClass) ( .Values.persistence.pv_static_nfs.enabled ) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.pv_static_nfs.enabled }}
  volumeName: {{ .Values.persistence.pv_static_nfs.name }}
  {{- end}}
{{- end }}
