apiVersion: v1
kind: Service
metadata:
  name: "{{ template "eldix.fullname" . }}-app-smtp"
  labels:
    app.kubernetes.io/name: {{ template "eldix.name" . }}
    helm.sh/chart: {{ include "eldix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: "{{ template "eldix.fullname" . }}-app-smtp"
      port: 8888
      protocol: TCP
      targetPort: 8888
      {{- if .Values.eldix.smtpNodePort }}
      nodePort: {{ .Values.eldix.smtpNodePort }}
      {{- end }}
  selector:
    app: "{{ template "eldix.fullname" . }}-app"
  type: NodePort
