apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-app"
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    helm.sh/chart: {{ include "eldix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: "{{ .Values.appName }}-app"
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: "{{ .Values.appName }}-app"
  type: ClusterIP
