apiVersion: v1
kind: Service
metadata:
  name: "{{ template "eldix.fullname" . }}-app-web"
  labels:
    app.kubernetes.io/name: {{ template "eldix.name" . }}
    helm.sh/chart: {{ include "eldix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: "{{ template "eldix.fullname" . }}-app-web"
      port: {{ default 80 .Values.eldix.service.web.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: "{{ template "eldix.fullname" . }}-app"
  type: "{{ default "ClusterIP" .Values.eldix.service.web.type }}"
